### PR TITLE
Move subscription form from Mailchimp to Sender

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

We're migrating to another email provider, sender, instead of Mailchimp. Mailchimp was very restrictive in the way campaigns could look, and they make you pay a lot more after 500 subscribers (we're at almost 400). Plus Mailchimp decided to increase their memberships by 20% starting February. At sender we'll pay $15 for 1500 subscribers, and the editor is almost the same as Mailchimp but less glitchy and with a plain email option (weirdly it doesn't exist in Mailchimp).

Also, we've received feedback about how Mailchimp gets blocked under Firefox strict setup. 

## Approach

I implemented a Netlify function that accesses Sender's API key stored in Netlify env variable. I also added a plausible tack event to subscribing. 

### Possible Drawbacks or Risks

Is this setup of the key safe enough? Unfortunately, Sender's API key cannot be restricted to use a single service but it has all permissions by default.

### CODE REVIEW

**Comment by taras** [comment]
@jorgelainfiesta this is the right way to protect the API key

**Comment by jorgelainfiesta** [comment]
Ok thanks! I was hesitant because you have access to netlify env vars in development when using `netlify-cli`, somebody could use it and access the email API. But maybe netlify-cli only lets you connect to a repo if you belong to the org?

**Comment by taras** [comment]
They would need to be part of our Netlify account. Without that, you can't access information from netlify-cli

**Review by jbolda — APPROVED** [review]
Looks good to me 👍. 

One comment that I don't think will change much but as an FYI, the functions run in a node environment that is new enough that you likely don't need to pull in axios and can use the built-in `fetch` directly. It doesn't much matter though because you are pulling it in as a dependency for the frontend anyways. It wouldn't need to include it in the netlify functions build, but I suspect it is negligible difference.

**Comment by jorgelainfiesta** [comment]
Sorry I haven't had the time to look into changing it to the node native fetch, I can maybe do it in a future PR

**Pull request merged**
