### PR TITLE
Adds article about interactors and design systems

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

Article about interactors and design systems

## Approach

Taras provided an outline, I wrote it out, Jeffrey edited, and Dmitry provided screenshots

### CODE REVIEW

**Review by taras — COMMENTED** [review]
image

is this missing js/ts text code highlighting?

image

Missing image.

**Comment by jorgelainfiesta** [comment]
I fixed the URL of that image, thanks! about the code highlighting, it does have JS but I guess the parser we have installed in this gatsby instance is bad.

**Comment by cherewaty** [comment]
New commits pushed that slim things down a lot: https://deploy-preview-148--frontside.netlify.app/blog/2021-08-04-interactors-design-systems/

<blockquote><div><strong><a href="https://frontside.com/blog/2021-08-04-interactors-design-systems/">Interactors: the design systems testing ally | Frontside</a></strong></div><div>Components from a design system make building UIs easy. It should be just as easy to test them. Interactors enable more robust tests for component-based UIs, and improve component libraries' maintainability.</div></blockquote>

**Review by taras — COMMENTED** [review]
@jorgelainfiesta @cherewaty this is literally perfect. wow. i have no words. let’s ship it!

**Review by taras — APPROVED** [review]
👍

**Comment by jorgelainfiesta** [comment]
Really good! thanks Jeffrey!

**Pull request merged**
