### PR TITLE
Add blog post on using webhooks to drive entity providers for backstage

### PR DESCRIPTION
**Pull request by minkimcello**
@JavierLainparty you'll need to update the photo on [this](https://github.com/thefrontside/frontside.com/compare/mk/backstage-provider?expand=1#diff-2181aad9d1068a9ffe6b8a5b0cb08d44723d63d9cb370dec03ba85a93fd9b0e1R11) line

### CODE REVIEW

**Review by taras — APPROVED** [review]
This looks really great

**Review by taras — APPROVED** [review]
👍

**Comment by minkimcello** [comment]
@taras olsen hasn't edited this article but if you think it's good to go, please go ahead and merge the PR

**Comment by taras** [comment]
@minkimcello we'll have @JavierLainparty edit it and then merge it.

**Comment by JavierLainparty** [comment]
Ok, it looks good to me!

**Pull request merged**
