### PR TITLE
feat: add discord bot commands

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

This implementation uses the webhooks and the Frontside Jack account shared with the team. The IDs included are public, and anything private is saved in Netlify. The commands need to be initialized if they are changed. See the `init-command.js` to POST changes (it is an upsert). Changes can be tested using `ntl dev --live` as a tunnel, but it be worth adding in a "test bot" in the future so we don't need to adjust the main bot.

## Approach

See https://discord.com/developers/docs/interactions/slash-commands for the docs.

This is what using the command looks like in discord.
image

And the response shows up like this (without noting who actually ran the command).
image

### Alternate Designs

A persistent hosted gateway bot can be alternatively used, but this is easiest to throw up. We can always switch over in the future if we so choose.

### TODOs and Open Questions

We may want to (now or in the future?) wrap this all in effection.

### CODE REVIEW

**Comment by jorgelainfiesta** [comment]
Sorry Jacob, I missed this until Charles pointed it out yesterday on the live version. I'm not really fond of the format, I feel it's a bit redundant because Discord already makes an announcement when a person joins the server. 

I'd honestly like the bot to send a private message to the new user to provide them with info about the server, and specially to ask them questions of who they are. That's the most critical part for me. I need to understand our audience, where are they coming from, what are they looking for.

**Comment by cowboyd** [comment]
@jorgelainfiesta Can you write out the text that you'd want to see, and then we can see about making it a DM?

**Comment by jorgelainfiesta** [comment]
People seem to be comfortable with the way [our RSVP form](https://backstage-openmic.com/rsvp) asks questions so maybe something like this:

— Welcome! it's great to have you here, what's your full name? 

_They type in their response, and it'd be great if we could append that info to their discord profile_

— What's your role and company?

_We can also append the response to their profile but not all that necessary_

— How did find out about Frontside's discord server?

_Can we offer options that they can click? BigTest's website, Frontside's blog, Github, A newsletter, A friend told me, Type other_

— Do you want to sign up for our newsletter? It's one email a month! 

_Yes / no_

— _If yes, otherwsie skip to next_ Cool! what's your work email? We won't share it with anyone.

_We can send it to mailchimp if possible_

— Great to have you around %name%! We have an #introductions channel, go say hi and share with us how we may help you!

_We can send the responses somewhere, like slack or a spreadsheet, whatever is easiest for now_

**Comment by cowboyd** [comment]
I could be wrong @jbolda but I think we would need to run a stateful bot to do this?

Also: @jorgelainfiesta such a stateful bot is a great use-case for effection!

**Comment by jbolda** [comment]
Yea, I think we will want to do this with a stateful bot. Any reason to have some slash commands still hosted separately on netlify?

**Comment by jbolda** [comment]
This was a fun experiment, but I think we are going to go a different direction with a discord bot (likely something stateful that is either an off-the-shelf option or hosted by us).

**Pull request closed without merging**
