### PR TITLE
Backstage DevContainers blogpost

### PR DESCRIPTION
**Pull request by minkimcello**
🤔

### CODE REVIEW

**Review by taras — APPROVED** [review]
👌

**Comment by minkimcello** [comment]
@jorgelainfiesta In the last commit: https://github.com/thefrontside/frontside.com/pull/176/commits/11004e53894bbf7528c45eb785b85cdf7ec45e77

- I removed `Tutorial:` from the title
- I modified the description (because it was contradicting what the blog was saying about how installing these dependencies is not that much of a hassle for linux and macos users)
- Changed some of the instances of DevContainers to dev container for consistency

If this looks good to you, i think this PR is ready to go.

**Comment by jorgelainfiesta** [comment]
@minkimcello thanks Min, it's looking good. Do you have strong feelings about removing the 'tutorial' part though? I'm thinking we can start building up reputation for people searching for 'backstage tutorial'

**Comment by jorgelainfiesta** [comment]
Also, I'm thinking we should publish it on Monday to focus this week on promoting Paul's article, and next week we promote this one.

**Comment by minkimcello** [comment]
Sure, I'll put the tutorial back in the title.

Do you know how can get the stable-urls to pass? I think it's complaining because I changed the name of the file?

**Comment by taras** [comment]
@minkimcello it's not giving a great error. I'm not sure if that's ok or not ok

**Comment by jorgelainfiesta** [comment]
> Do you know how can get the stable-urls to pass? I think it's complaining because I changed the name of the file?

You have to run `netlify build` for it to compile the sitemap again. We forgot to add that to the readme

**Pull request merged**
