### PR TITLE
Remove blockchain blog post

### PR DESCRIPTION
**Pull request by cherewaty**
Removes blockchain post and author page.

### CODE REVIEW

**Comment by cherewaty** [comment]
I guess https://github.com/thefrontside/frontside.com/pull/102 didn't make it on to the `production` branch?

**Comment by cherewaty** [comment]
@jorgelainfiesta do I need to set up any redirects?

**Review by taras — APPROVED** [review]
👍

**Comment by jorgelainfiesta** [comment]
> @jorgelainfiesta do I need to set up any redirects?

Yeah it's not great to have broken links, specially because this one is indexed on search engines already. Can we redirect the article url to `/blog` and the profile to `/about`?

**Pull request merged**
