### PR TITLE
Add blog post about patching Backstage lint command to output a summary file

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation

I worked with a client that had an insane amount of lint errors amassed in their Backstage project so I had to come up with a solution of being able to fix those errors without putting a stop to development while trying to prevent the list of errors from growing.

### CODE REVIEW

**Comment by minkimcello** [comment]
@taras I think the workflows might be failing because a forked repo doesn't have access to github actions secret?

**Comment by taras** [comment]
@minkimcello what do you think about this image? 

Prompt: [Technical diagram with a dominant color palette of blues, teals, and purples, on a saturated dark background. Depict a mountain made of tangled code lines symbolizing linting errors. The image should have a structured flow with distinct icons and element, and subtle gradients for depth.](https://www.midjourney.com/app/jobs/94a6ee7e-3d2c-43df-84b7-4d514b8d5c31/)

technical-diagram-midjourney

Prompt: [the art of crystal mountain, in the style of precision-oriented geometric forms, soft gradients, isometric, dark azure and ruby, columns and totems, digital gradient blends, light blue and silver, few objects](https://www.midjourney.com/app/jobs/af626de0-97bb-40c9-889f-a9691ed6dbf9/)

tarasm_the_art_of_crystal_mountain_in_the_style_of_precision-or_af626de0-97bb-40c9-889f-a9691ed6dbf9

**Comment by minkimcello** [comment]
@taras I like the first one. Second one is great too but it looks generic enough for you to save it and use it for another blog post.

Would the first one go well with the theme of the site? It's the only one with a black background.

**Comment by taras** [comment]
> It's the only one with a black background.

yeah, it's true. let me play around with it some more.

**Comment by taras** [comment]
@minkimcello how about these? 
image

**Comment by minkimcello** [comment]
> @minkimcello how about these? image

bottom left 🔥 because it looks most like a bar chart and the other ones are too 3D and complex for the context of the blog post

**Comment by taras** [comment]
Technical diagram with a dominant color palette of greens, yellows, and reds, on light blue background. Depict one dominant mountain made of tangled code lines symbolizing linting errors. The image should have a structured flow with distinct icons and element, and subtle gradients for depth.

How is this?

**Comment by taras** [comment]
It looks too dark, I think we need a lighter version 
image

**Comment by taras** [comment]
@minkimcello what do you think about this 

image

**Comment by minkimcello** [comment]
Oh yeah, it is a little dark. 

> @minkimcello what do you think about this
> 
> image

top left

**Comment by taras** [comment]
[Technical diagram with a dominant color palette of greens, yellows, and reds. light blue background with a gradient; Depict one dominant mountain made of tangled code lines symbolizing linting errors. The image should have a structured flow with distinct icons and element, and subtle gradients for depth.](https://www.midjourney.com/app/jobs/eb63245d-d5d1-4a22-828b-c6f6610b4b4d/)

**Comment by taras** [comment]
@minkimcello here is another one, that I made to show progression from red -> yellow -> green. Choose whichever you like better. 

[Technical diagram with a dominant color palette of reds on left, yellows in middle and greens on right. light blue background with a gradient; Depict one dominant mountain made of tangled code lines symbolizing linting errors. The image should have a structured flow with distinct icons and element, and subtle gradients for depth.](https://www.midjourney.com/app/jobs/cc0e1e4f-54bb-40ba-ab58-7248245cb184/)

**Comment by minkimcello** [comment]
> @minkimcello here is another one, that I made to show progression from red -> yellow -> green. Choose whichever you like better.
> 
> [](https://www.midjourney.com/app/jobs/cc0e1e4f-54bb-40ba-ab58-7248245cb184/)Technical diagram with a dominant color palette of reds on left, yellows in middle and greens on right. light blue background with a gradient; Depict one dominant mountain made of tangled code lines symbolizing linting errors. The image should have a structured flow with distinct icons and element, and subtle gradients for depth.

Oh yah that's nice

**Review by taras — CHANGES_REQUESTED** [review]
I'm sorry it took so long to review this. It's a great topic, I wanted to share a few thoughts.

1. It would be helpful to start the post with a summary and then go into the introduction. Maybe we can start with a TL;DR
2. The post dives quickly into the "how" but we should first cover the "what". On other words, we should provide a high-level overview of the approach before diving into details.
3. The code blocks are very long. Is it possible to create a demo of this setup and point at specific commits?

Thank you for your contribution

**Comment by minkimcello** [comment]
> 1. It would be helpful to start the post with a summary and then go into the introduction. Maybe we can start with a TL;DR

Added a TL;DR - https://github.com/thefrontside/frontside.com/pull/289/commits/17842a1d09634db7dc5cdf18386c1987526904d4

> 2. The post dives quickly into the "how" but we should first cover the "what". On other words, we should provide a high-level overview of the approach before diving into details.

There was a [high level view of the patch](https://github.com/thefrontside/frontside.com/pull/289/files#diff-cb6b0ff0001a526d4b9b120ea04cae89708706018554b354660ff62fb9243536R41-R52). Is that what you were talking about? Or did you mean high level overview of the whole blog post? If so, is that covered by the new tl;dr now?

> 3. The code blocks are very long. Is it possible to create a demo of this setup and point at specific commits?

Created a separated repository for it and kept the patch in the blog post - https://github.com/thefrontside/frontside.com/pull/289/commits/b13a0c8f25f549e396386fa1334aa8c12cf9d741

- [Demo Repository](https://github.com/minkimcello/backstage-lint-demo)
- [Patch File](https://github.com/minkimcello/backstage-lint-demo/blob/main/patches/%40backstage%2Bcli%2B0.22.12.patch)
- [Commit History](https://github.com/minkimcello/backstage-lint-demo/commits/main)

**Review by taras — APPROVED** [review]
This looks great. Let's fix the sitemap, and we can merge it today.

**Pull request merged**
