### PR TITLE
feat: bigtest

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

Implementing BigTest to help us confirm that the links between pages work as expected. Also a natural place to test and serve as an example.

### CODE REVIEW

**Comment by cowboyd** [comment]
@jbolda that's a strange error. It looks like the app isn't running on 127.0.0.1:8888?

**Comment by jbolda** [comment]
> @jbolda that's a strange error. It looks like the app isn't running on 127.0.0.1:8888?

Yea, I think I might need to separately start up the gatsby server? I wasn't having BigTest do that because it takes forever to start up and it was faster to leave it running.

**Comment by jbolda** [comment]
Well, I think I have taken this to the point of working as best as we can right now. It runs locally, but seems to fail in CI. I am going to disable the CI run until we get this issue resolved. At least we can move forward merging this in and come back around and update when it is fixed.

**Comment by jorgelainfiesta** [comment]
Wonderful! how did we end up managing the screen size? it seems that the tests are against the desktop version or is it reaching into the collapsed nav?

**Comment by jbolda** [comment]
> Wonderful! how did we end up managing the screen size? it seems that the tests are against the desktop version or is it reaching into the collapsed nav?

We can't really manage it right now. Locally you can run it in `chrome` and manually adjust the size. In CI, I have it run in `chrome.headless` which appears to use a window size small enough that it enables the mobile menu. On the test, you can see that I click on the menu button after navigating to the page. The unfortunate effect of this is that if we run it locally with a window big enough the test will likely fail (unless we comment out the menu button click).

**Review by jorgelainfiesta — APPROVED** [review]

**Pull request merged**
