### PR TITLE
Adds Code of Conduct and Privacy Policy to the site

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

We were missing a Code of Conduct for your community efforts, and a Privacy Policy for the website.

## Approach 

I used [Contributor Covenant](https://www.contributor-covenant.org) code as it was the most popular among OSS projects for the Code of Conduct. The Privacy Policy I used a generator and inputed what we use on the website (mainly Google Analytics) and the contact form. 

[Preview of Code of Conduct](https://deploy-preview-112--frontside.netlify.app/code-of-conduct)
[Preview of Privacy Policy](https://deploy-preview-112--frontside.netlify.app/privacy-policy)

### CODE REVIEW

**Review by taras — APPROVED** [review]
👍

**Comment by cowboyd** [comment]
Looks great! I have two requests:

1. Let's get rid of all the _In Short:_   from there. The leader being in italics is enough to say "in short" without saying it and becoming repetitive.
2. 
> Legitimate Interests: We may process your data when it is reasonably necessary to achieve our legitimate business interests.

This is the only really shady piece of the privacy policy. To me this says "If it benefits us, and it's legal, we may do it" . If I were reading this, I'd feel like pretty much any thing goes and that this would be kinda icky.

**Comment by jorgelainfiesta** [comment]
1. Sure, no problem.
2. I understand what you mean, but there's also other clauses in which we explain we will not sell their data, for example. We'll just contact them and probably run analytics to understand user engagement on the website. I can't even think of what else we can do with data, should we change this ambiguous lawyer-written (probably on purpose) to a more technically informed sentence but who has no law consciousness? or do we want to call a lawyer to review this?

**Comment by cowboyd** [comment]
If in doubt, let's leave it out, and then we can have a lawyer look at it if we feel then need? We can have a disclaimer that we can change it at any point, right?

**Comment by jorgelainfiesta** [comment]
Yeah I honestly don't think we need a lawyer for this, it's just a generic policy we don't make anything special.

**Review by cowboyd — APPROVED** [review]
🤓

**Pull request merged**
