### PR TITLE
New website

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

New website styles

## Approach

We've created all styles from scratch using vanilla-extract. Copy has been revised by Olson. Analytics by plausible are in place. Forms are from typeform. 

## TODO

- [x] Case study
- [x] SSR issue in page with animation

### CODE REVIEW

**Review by taras — APPROVED** [review]

**Comment by cowboyd** [comment]
This website is 🤯🤯🤯 The visual language of the illustrations has really come along and brilliantly (both literally and figuratively) augments the messaging. I really love it.

I had a single moment while reading that wasn't pure satisfaction

"DEVELOPER EXPERIENCE:  WHERE DELIVERIES AND RETENTION MEET" falls flat for me. There is too little context around the two words. My first thought was of grocery or pizza deliveries, and retention I kind of got, but not super strong. It may take more words, but we have to more firmly point at these concepts.

- Developer Experience: Are your developers hooked on shipping your product?
- Developer Experience: Are your developers delighted to ship code for you?
- Developer Experience: Delighted developers ship better code sooner, and stay with you longer.

**Comment by jorgelainfiesta** [comment]
Thanks @cowboyd ! that's good feedback. We must really keep it short though. Maybe we can boil down some of your ideas to use less words. For instance, saying 'developers` twice in the title takes too much space. I'll keep trying to think of something else, and please do share more ideas when you get them!

**Comment by taras** [comment]
@jorgelainfiesta I'm ok with the title as is, just maybe a slight adjustment: "Developer Experience: where delivery and retention meet". I had a funny one that came to mind: `Developer Experience: make grass greener here` 😆

**Comment by jbolda** [comment]
> @jorgelainfiesta I'm ok with the title as is, just maybe a slight adjustment: "Developer Experience: where delivery and retention meet". I had a funny one that came to mind: `Developer Experience: make grass greener here` 😆

Can we make it change to funny ones after 30s? 😆

**Comment by taras** [comment]
@jorgelainfiesta with that said, I'm not 100% certain that the current tagline gets a clear point across.

**Comment by jorgelainfiesta** [comment]
Let's see if we can come up with something this week. If not, we can still release it and ask people we know what they think, and iterate from there

**Pull request merged**
